name: Trigger Opsera GitCustodian Scan and Report to GitHub

on:
  workflow_dispatch:

jobs:
  trigger-opsera-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitCustodian Scan in Opsera
        id: trigger_scan
        run: |
          response=$(curl -s -X POST "https://app.opsera.io/api/v1/pipeline/run" \
          -H "Authorization: Bearer ${{ secrets.OPSERA_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"pipelineId": "68232d25a85372e8342b3100"}')
          echo "Pipeline Response: $response"
          if echo "$response" | jq . >/dev/null 2>&1; then
            run_count=$(echo $response | jq -r '.runCount')
            echo "run_count=$run_count" >> $GITHUB_ENV
          else
            echo "Error: Invalid JSON response. Exiting." >&2
            exit 1
          fi

  monitor-opsera-scan:
    needs: trigger-opsera-scan
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Opsera Scan Completion
        id: check_status
        run: |
          status="running"
          while [ "$status" == "running" ] || [ "$status" == "queued" ]; do
            sleep 30
            response=$(curl -s -X POST "https://app.opsera.io/api/v1/pipeline/status" \
            -H "Authorization: Bearer ${{ secrets.OPSERA_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"pipelineId": "68232d25a85372e8342b3100", "runCount": "${{ env.run_count }}"}')
            if echo "$response" | jq . >/dev/null 2>&1; then
              status=$(echo $response | jq -r '.status // "unknown"')
              echo "Current Status: $status"
            else
              echo "Error: Invalid JSON response during status check. Exiting." >&2
              exit 1
            fi
          done
          echo "final_status=$status" >> $GITHUB_ENV

  report-scan-result:
    needs: monitor-opsera-scan
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub Actions Job Status
        if: env.final_status == 'success'
        run: echo "✅ GitCustodian Scan Passed"

      - name: Set GitHub Actions Job Status
        if: env.final_status != 'success'
        run: echo "❌ GitCustodian Scan Failed"

  comment-scan-result:
    needs: monitor-opsera-scan
    runs-on: ubuntu-latest
    steps:
      - name: Comment on GitHub Pull Request
        if: github.event_name == 'pull_request'
        run: |
          curl -s -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"body": "GitCustodian Scan Result: ${{ env.final_status }}"}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
