name: Trigger Opsera GitCustodian Scan and Report to GitHub

on:
  workflow_dispatch:

jobs:
  trigger-opsera-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitCustodian Scan in Opsera
        id: trigger_scan
        run: |
          response=$(curl -s -X POST "https://app.opsera.io/api/v1/pipeline/run" \
          -H "Authorization: Bearer ${{ secrets.OPSERA_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"pipelineId": "68232d25a85372e8342b3100"}')
          echo "Pipeline Response: $response"
          if echo "$response" | jq . >/dev/null 2>&1; then
            run_count=$(echo $response | jq -r '.runCount')
            echo "run_count=$run_count" >> $GITHUB_ENV
          else
            echo "Error: Invalid JSON response. Exiting." >&2
            exit 1
          fi

  fetch-opsera-logs:
    needs: trigger-opsera-scan
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Opsera Scan Logs
        id: fetch_logs
        run: |
          response=$(curl -s -X POST "https://app.opsera.io/api/v1/pipeline/logs" \
          -H "Authorization: Bearer ${{ secrets.OPSERA_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"pipelineId": "68232d25a85372e8342b3100", "runCount": "${{ env.run_count }}"}')
          
          if echo "$response" | jq . >/dev/null 2>&1; then
            logs=$(echo $response | jq -r '.logs // "No logs available"')
            echo "logs=$logs" >> $GITHUB_ENV
          else
            echo "Error: Unable to fetch logs. Exiting." >&2
            exit 1

  report-scan-result:
    needs: fetch-opsera-logs
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub Actions Job Status
        run: |
          if [ "${{ env.logs }}" != "No logs available" ]; then
            echo "✅ GitCustodian Scan Completed"
          else
            echo "❌ GitCustodian Scan Failed: No logs available"
            exit 1

      - name: Create Detailed Scan Report
        if: ${{ env.logs != 'No logs available' }}
        run: |
          echo "### GitCustodian Scan Report" > scan-report.md
          echo "Pipeline ID: $GITHUB_RUN_ID" >> scan-report.md
          echo "Scan Status: Completed" >> scan-report.md
          
          # Extract and include detailed error information from logs
          echo "#### Scan Issues:" >> scan-report.md
          echo "${{ env.logs }}" | jq -r '.[] | "\(.Author) \t \(.Commit) \t \(.CommitHash) \t \(.Path) \t \(.LineNumber) \t \(.Link) \t \(.Reason) \t \(.Severity) \t \(.IssueStatus)"' >> scan-report.md
          echo "#### End of Report" >> scan-report.md

      - name: Commit the Scan Report
        if: ${{ env.logs != 'No logs available' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add scan-report.md
          git commit -m "Add detailed scan report"
          git push

  comment-scan-result:
    needs: fetch-opsera-logs
    runs-on: ubuntu-latest
    steps:
      - name: Comment on GitHub Pull Request
        if: github.event_name == 'pull_request'
        run: |
          curl -s -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"body": "GitCustodian Scan Result: Completed\n\nDetailed Logs:\n${{ env.logs }}"}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
